#!/usr/bin/env bash
#Connecting 2nd server
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

HOSTNAME=$(hostname)
sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
