#!/usr/bin/env bash
# Installs Nginx and creates the required Holberton School home page.
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
