#!/usr/bin/env bash
# Installs Nginx and creates the required Holberton School home page.

apt-get update
apt-get install -y nginx

printf '%s\n' 'Holberton School for the win!' > /var/www/html/index.html

service nginx restart
