#!/usr/bin/env bash
#Create 404 not found page
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server/a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
